# Generated by Django 5.1 on 2024-08-15 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("profile", models.TextField()),
                ("about", models.TextField()),
                ("degree", models.CharField(max_length=100)),
                ("college", models.CharField(max_length=100)),
                ("degree_year", models.CharField(max_length=100)),
                ("organization", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("exp_year", models.CharField(max_length=100)),
                ("project", models.CharField(max_length=100)),
                ("desc", models.TextField()),
                ("skill", models.TextField()),
                ("tool", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="myapp.user",
                    ),
                ),
            ],
        ),
    ]
