# Generated by Django 5.1.1 on 2024-10-09 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='college',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree_year',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='exp_year',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='project',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='tool',
        ),
        migrations.AlterField(
            model_name='resume',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('degree_year', models.CharField(max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='myapp.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('exp_year', models.CharField(max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='myapp.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='myapp.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='myapp.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='myapp.resume')),
            ],
        ),
    ]
