# Generated by Django 5.1.1 on 2024-10-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_resume_college_remove_resume_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exp_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
